//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave_by_ProSoft.Localization {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave_by_ProSoft.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Differential.
        /// </summary>
        public static string BackupTypeDifferential {
            get {
                return ResourceManager.GetString("BackupTypeDifferential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Full.
        /// </summary>
        public static string BackupTypeFull {
            get {
                return ResourceManager.GetString("BackupTypeFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup Work Management.
        /// </summary>
        public static string BackupWorkManagement {
            get {
                return ResourceManager.GetString("BackupWorkManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete job.
        /// </summary>
        public static string BackupWorkManagementDeleteBackupSelected {
            get {
                return ResourceManager.GetString("BackupWorkManagementDeleteBackupSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        public static string BackupWorkManagementName {
            get {
                return ResourceManager.GetString("BackupWorkManagementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a new backup job.
        /// </summary>
        public static string BackupWorkManagementNewBackup {
            get {
                return ResourceManager.GetString("BackupWorkManagementNewBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Progress (%).
        /// </summary>
        public static string BackupWorkManagementProgressPercentage {
            get {
                return ResourceManager.GetString("BackupWorkManagementProgressPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source.
        /// </summary>
        public static string BackupWorkManagementSource {
            get {
                return ResourceManager.GetString("BackupWorkManagementSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Launch selected job.
        /// </summary>
        public static string BackupWorkManagementStartBackupSelected {
            get {
                return ResourceManager.GetString("BackupWorkManagementStartBackupSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Status.
        /// </summary>
        public static string BackupWorkManagementStatus {
            get {
                return ResourceManager.GetString("BackupWorkManagementStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Target.
        /// </summary>
        public static string BackupWorkManagementTarget {
            get {
                return ResourceManager.GetString("BackupWorkManagementTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        public static string BackupWorkManagementType {
            get {
                return ResourceManager.GetString("BackupWorkManagementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Browse....
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The management software is running. The backup job will be paused after processing the file .
        /// </summary>
        public static string BusinessApplicationError {
            get {
                return ResourceManager.GetString("BusinessApplicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name of the business software process to be monitored :.
        /// </summary>
        public static string BusinessSoftwareCheckSetting {
            get {
                return ResourceManager.GetString("BusinessSoftwareCheckSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup type.
        /// </summary>
        public static string ConfigNewJobBackupType {
            get {
                return ResourceManager.GetString("ConfigNewJobBackupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extensions to encrypt (comma separated) :.
        /// </summary>
        public static string ConfigNewJobEncryptExtensions {
            get {
                return ResourceManager.GetString("ConfigNewJobEncryptExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        public static string ConfigNewJobName {
            get {
                return ResourceManager.GetString("ConfigNewJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source directory.
        /// </summary>
        public static string ConfigNewJobSourceDirectory {
            get {
                return ResourceManager.GetString("ConfigNewJobSourceDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Target directory.
        /// </summary>
        public static string ConfigNewJobTargetDirectory {
            get {
                return ResourceManager.GetString("ConfigNewJobTargetDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validate the creation.
        /// </summary>
        public static string ConfigNewJobValidate {
            get {
                return ResourceManager.GetString("ConfigNewJobValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmation.
        /// </summary>
        public static string ConfirmationTitle {
            get {
                return ResourceManager.GetString("ConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurred while trying to restart the application. Please restart it manually..
        /// </summary>
        public static string ErrorRestartingApplicationMessage {
            get {
                return ResourceManager.GetString("ErrorRestartingApplicationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File extensions to encrypt by default (comma separated) :.
        /// </summary>
        public static string ExtensionFileCryptSetting {
            get {
                return ResourceManager.GetString("ExtensionFileCryptSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à General settings.
        /// </summary>
        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Information.
        /// </summary>
        public static string InformationTitle {
            get {
                return ResourceManager.GetString("InformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language change has been cancelled. The current language remains active..
        /// </summary>
        public static string LanguageChangeCancelledMessage {
            get {
                return ResourceManager.GetString("LanguageChangeCancelledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The application needs to restart the main window to apply the language change. Do you want to restart it now ?.
        /// </summary>
        public static string LanguageChangeRestartMessage {
            get {
                return ResourceManager.GetString("LanguageChangeRestartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log file format :.
        /// </summary>
        public static string LogFileFormatSetting {
            get {
                return ResourceManager.GetString("LogFileFormatSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup management.
        /// </summary>
        public static string MainBackupManagement {
            get {
                return ResourceManager.GetString("MainBackupManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quit.
        /// </summary>
        public static string MainQuit {
            get {
                return ResourceManager.GetString("MainQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string MainSettings {
            get {
                return ResourceManager.GetString("MainSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup job deleted..
        /// </summary>
        public static string MessageBoxDeleteJob {
            get {
                return ResourceManager.GetString("MessageBoxDeleteJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Selected job finish.
        /// </summary>
        public static string MessageBoxLaunchJob {
            get {
                return ResourceManager.GetString("MessageBoxLaunchJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New backup job validated !.
        /// </summary>
        public static string MessageNewJobValidated {
            get {
                return ResourceManager.GetString("MessageNewJobValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the source folder.
        /// </summary>
        public static string MessageSelectSourceFolder {
            get {
                return ResourceManager.GetString("MessageSelectSourceFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the target folder.
        /// </summary>
        public static string MessageSelectTargetFolder {
            get {
                return ResourceManager.GetString("MessageSelectTargetFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings saved successfully..
        /// </summary>
        public static string SettingsSaved {
            get {
                return ResourceManager.GetString("SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings validated..
        /// </summary>
        public static string SettingsValidatedMessage {
            get {
                return ResourceManager.GetString("SettingsValidatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validate the settings.
        /// </summary>
        public static string ValidateSettings {
            get {
                return ResourceManager.GetString("ValidateSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warning !.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
