name: Build and Release Installer

on:
  push:
    branches:
      - main
      # - dev
  workflow_dispatch:

jobs:
  build:
    name: Build and Package
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore EasySave/EasySave.sln

      - name: Publish app (self-contained)
        run: dotnet publish EasySave/EasySave.sln -c Release -r win-x64 --self-contained true -o ./publish

      - name: Download and Install Inno Setup
        run: |
          Invoke-WebRequest -Uri "https://jrsoftware.org/download.php/is.exe" -OutFile "is.exe"
          Start-Process -Wait -FilePath ".\is.exe" -ArgumentList "/VERYSILENT", "/SUPPRESSMSGBOXES", "/NORESTART", "/SP-"

      - name: Build installer with Inno Setup
        run: |
          $InnoSetupPath = (Get-ChildItem -Path "C:\Program Files (x86)" -Recurse -Filter "ISCC.exe").FullName
          & $InnoSetupPath "installer\EasySave.iss"
        
      - name: Verify Inno Setup Installation
        run: |
          if (!(Test-Path "C:\Program Files (x86)\Inno Setup 6\ISCC.exe")) {
              Write-Error "Inno Setup installation failed. ISCC.exe not found."
          }
      
      - name: Upload installer as artifact
        uses: actions/upload-artifact@v4
        with:
          name: EasySave_Installer
          path: Installer/EasySave_Installer_v1.1.0.exe
